export const Quotes = [
	"Whatever you are seeking, is seeking you",
	"What is planted in each person’s soul will sprout.",
	"There is nothing outside of yourself, Look within, Everything you want is there- you are That",
	"Until you remain blind and deaf I will be invisible.",
	"Look for the answer inside your question",
	"Eyes cannot see you. You are the source of sight",
	"Whatever I was looking for was always you.",
	"Your calling my name is My reply. Your longing for Me is My message to you",
	"I see my beauty in you. I become a mirror that cannot close it’s eyes to your longing",
	"Be foolishly in love, because love is all there is.",
	"At the end of my life, with just one breath left, if you come, I’ll sit up and sing.",
	"A lover wants only to be in love’s presence.",
	"When you see a scowling face, it is not a lover’s",
	"Submit to love without thinking",
	"I see my Beauty in you.",
	"I can be without anyone but not without You",
	"You have Within you more love than you could ever understand.",
	"The real beloved is that one who is unique, who is your beginning and your end.",
	"Goodbyes are only for those who love with their eyes.Because for those who love with heart and soul there is no such thing as separation!",
	"In fact, my soul and yours are the same, You appear in me, I in you, We hide in each other.",
	"Lovers don’t finally meet somewhere. They’re in each other all along",
	"Close your eyes, fall in Love, stay there",
	"I once had a thousand desires, but in my one desire to know you,all else melted away.",
	"When love itself comes to kiss you, don’t hold back!",
	"Don’t be fooled by my beauty—the light of my face comes from the candle of my spirit.",
	"There’s a path from your heart to mine.",
	"In truth, everything and everyone is a shadow of the Beloved.",
	"Speak with the language of love",
	"Don’t plant anything but love",
	"Travel brings power and love back into your life.",
	"If the house of the world is dark, Love will find a way to create windows.",
	"From understanding comes Love.",
	"Only LOVE is infinite.",
	"I belong to no religion.My religion is Love. Every heart is My temple.",
	"When I am with you, everything is prayer.",
	"Both light and shadow are the dance of love.",
	"Love a silent language.",
	"Love is an emotion. totally silent and inexpressible with words.",
	"Come out of the circle of time. And into the circle of Love.",
	"In every religion there is love,yet love has no religion.",
	"When you seek love with all your heart,you shall find it’s echoes across the universe.",
	"I am a child of love.",
	"My Heart is your student, it studies Love.",
	"Wherever you are, and whatever you do,be in love.",
	"When you find Love, you will find yourself",
	"Love risks everything and asks for nothing.",
	"Love will find its way through all languages on its own",
	"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
	"Love calls – everywhere and always.",
	"Every day is just perfect for love",
	"On a day when the wind is perfect, the sail just needs to open and the world is full of beauty. Today is such a day.",
	"As you live deeper in the heart, the mirror gets clearer and cleaner",
	"I want to be where our bare foot walks, because maybe before you step, you will look at the ground. I want that Blessing",
	"Open your eyes, for this world  is only a dream.",
	"Now’ is where Love Breathes.",
	"With friends you grow wings.",
	"The heart is the secret inside the secret.",
	"Every step of the way I will walk with you and never leave you stranded",
	"You transform all those who are touched by you.",
	"Live in harmony with everyone; Be friendly with everyone",
	"The one who have a good friend doesn’t need any mirror.",
	"If you are looking for a friend who is faultless, you will be friendless.",
	"Be with those who help your being..",
	"When I am silent, I have thunder hidden inside.",
	"Be silent,  Only the Hand of God can remove the burdens of your heart",
	"No words can explain how inspired words spring out of silence",
	"Protect yourself from your own thoughts.",
	"Enough of Words.Come to me without a sound.",
	"Sit, be still, and listen.",
	"Hear the passage into silence and be that.",
	"You are the seeker, the goal, and seeking itself.",
	"Only from the heart can you touch the sky.",
	"There is a window from one Heart to another Heart.",
	"Purify your eyes, and see the pure world.  Your life will fill with radiant forms.",
	"I am Lost in God and God is found in me.",
	"Your noise is my silence.",
	"Don’t sit and wait. Get out there, feel life. Touch the sun, and immerse in the sea.",
	"Give yourself a kiss. If you want to hold the beautiful one, hold yourself to yourself.",
	"You are not a drop in the ocean. You are the entire ocean in a drop.",
	"The Lamps are different, but the Light is the same.",
	"Strip away your pride and put on humble clothes",
	"Ordinary eyes categorize human beings",
	"Seeing You Heals Me",
	"We often need to be refreshed",
	"The moment you accept what troubles you’ve been given, the door will Open",
	"Respond to every call that excites your spirit.",
	"Everything about yesterday has gone with yesterday. Today, it is needed to say new things.",
	"If you are irritated by every rub, how will you be polished?",
	"Don’t grieve, anything you lose comes round in another form",
	"Every step I take is a Blessing",
	"With grief waved away, sweet gratefulness arrives.",
	"Something opens our wings. Something makes boredom and hurt disappear.",
	"Smiles come best from those who weep",
	"Do not be satisfied with the stories that come before you. Unfold your own myth.",
	"Beauty surrounds us.",
	"Yesterday I was clever, so I wanted to change the world. Today I am wise, So I Am Changing Myself",
	"Woman is the light of God, not just the beloved. It is as she is creative, not be created.",
];